languageCode: "en"
title: "bullframe.css"
baseURL: "https://github.com/marcop135/bullframe.css"

enableRobotsTXT: true
metaDataFormat: "yaml"

publishDir: "_gh_pages"

params:
  description: "Solid, fluid, IE-friendly (S)CSS framework"
  authors: "Marco Pontili"

  current_version: "3.0.0"
  repo: "https://github.com/marcop135/bullframe.css"

download:
  source: "https://github.com/marcop135/bullframe.css/archive/master.zip"
  dist: "https://github.com/marcop135/bullframe.css/releases/tag/v3.0.0/bullframe-css-master.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css: "https://cdn.jsdelivr.net/gh/marcop135/bullframe.css/bullframe.min.css"
  css_hash: "sha384-xL9PVrDQt5lFLFaPOMR1xJKpBz83hP1cjuND8oIMxl3kIM6yFyp7xzRChkB5ugUN"
