# GitHub Action that runs stylelint
# https://github.com/marketplace/actions/stylelinter
- name: stylelinter
  uses: actions-hub/stylelint@v1.1.2

# GitHub Action for Lighthouse Auditing
# https://github.com/marketplace/actions/lighthouse-audit
- name: Lighthouse Audit
  uses: jakejarvis/lighthouse-action@v0.3.2

# Automatically fixes typos and mistakes in your source code and docs!
# https://github.com/marketplace/actions/misspell-fixer-action
- name: misspell-fixer-action
  uses: sobolevn/misspell-fixer-action@0.1.0
